config/routes.rb
Rails.application.routes.draw do
  
  root :to => "homes#top"
  get "about", to: "homes#about", as: "about"
  resources :items, only: [:index,:show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  
  # cart_items routes
  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete "cart_items", to: "cart_items#destroy_all", as: "destroy_all_cart_items"
  

  # orders routes
  resources :orders, only: [:new, :create, :index, :show] do 
    collection do
      get :confirm
      get :complete
    end
  end
  
  # customers routes
  get "customers/mypage", to: "customers#show", as: "customer_mypage"
  get "customers/confirm", to: "customers#confirm", as: "customer_confirm"
  get "customers/edit", to: "customers#edit", as: "customer_edit"
  patch "customers", to: "customers#update", as: "customer_update"
  
  
  
  namespace :admin do
    root :to => "homes#top"
    resources :genres, only: [:index,:create,:edit,:update]
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end
  
  
  devise_for :customers, controllers: {
    sessions:        'customers/sessions',
    passwords:       'customers/passwords',
    registrations:   'customers/registrations',
  }
  
  devise_for :admins, path: "admin",controllers: {
    sessions:        'admins/sessions',
    passwords:       'admins/passwords',
    registrations:   'admins/registrations',
  }
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items , dependent: :destroy
  has_many :orders     , dependent: :destroy
  has_many :addresses  , dependent: :destroy
  
  validates :last_name         ,presence: true
  validates :first_name        ,presence: true
  validates :last_name_kana    ,presence: true
  validates :first_name_kana   ,presence: true
  validates :postal_code       ,presence: true
  validates :address           ,presence: true
  validates :telephone_number  ,presence: true
  validates :is_active                        , inclusion: [true,false]
  
  def full_name
    return last_name + first_name
  end
  
  def full_kana_name
    return last_name_kana + first_name_kana
  end
  
  def active_for_authentication?
    super && is_active
    
  end
  
  
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
    @customers = Customer.order("created_at DESC").page(params[:page])
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "customer info was successfully updated"
      redirect_to(admin_customer_path(@customer.id))
    else
      err_msg = "error! Failed to update data\n"
      @customer.errors.full_messages.each do |msg|
        err_msg += msg + "\n"
      end
      flash[:alert] = err_msg
      render :edit
    end
      
    
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, \
                                     :address, :telephone_number, :email, :is_active)
  end
  
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  
  skip_before_action :authenticate_customer!
  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  
  skip_before_action :authenticate_customer!
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = current_customer
  end
  
  def edit
    @customer = current_customer
  end
  
  def update
    @customer = current_customer
    
    if params[:is_deactivation?]
      @customer.update(is_active: false) 
      flash[:notice] = "Account is successfully deleted"
      sign_out_and_redirect(current_customer)
      
    else
      logger.debug "あじぇおｆ"
      logger.debug customer_params

      if @customer.update(customer_params) 
        flash[:notice] = "Data is successfully updated"
        redirect_to customer_mypage_path
        
      else
        err_msg = "error! Failed to update data\n"
        @customer.errors.full_messages.each do |msg|
          err_msg += msg + "\n"
        end
        flash[:alert] = err_msg
        render :edit
      end
    
    end
    
  end
  
  def confirm
    @customer = current_customer
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, \
                  :postal_code, :address, :telephone_number, :email, :is_active)
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/confirm.html.erb
<div class="container px-2">
  
  <div class=" my-4 mx-2 row d-flex justify-content-center mt-5 pt-5">
    <h3 class="font-weight-bold">本当に退会しますか？</h3>
  </div>

  <div class="row mx-2 d-flex justify-content-center py-2">    
    <p class="text-center">
      退会すると、会員登録情報や、<br>
      これまでの購入履歴が閲覧できなくなります。<br>
      退会する場合は、「退会する」をクリックしてください。
    </p>
  </div>
  <div class="row justify-content-center mb-5 pb-5 pt-3">
    <%= link_to("退会しない", customer_mypage_path, class: "btn btn-primary btn-md d-block mr-3") %>
    <%= link_to("退会する", customer_update_path(is_deactivation?: true), method: :patch, data: {confirm: "本当に退会しますか？"}, class: "btn btn-danger btn-md d-block ml-3") %>
  </div>
</div>

app/views/customers/edit.html.erb
<div class="container px-2">
  
  <div class=" my-4 mx-2 row d-flex justify-content-start">
    <h2>会員情報編集</h2>
  </div>
  
  <%= form_with(model: @customer, url: customer_update_path, local: true) do |f| %>
  
    <div class="my-4 mx-2 form-group row d-flex small justify-content-start">
      <%= f.label :last_name, "氏名", class: "col-3 col-form-label" %>
      <div class="col-4 form-inline">
        <%= f.text_field :last_name, class: "form-control w-75" %>
      </div>
      <div class="col-4 form-inline">
        <%= f.text_field :first_name, class: "form-control w-75" %>
      </div>
    </div>
    
    <div class="my-4 mx-2 form-group row d-flex small justify-content-start">
      <%= f.label :last_name_kana, "フリガナ", class: "col-3 col-form-label" %>
      <div class="col-4 form-inline">
        <%= f.text_field :last_name_kana, class: "form-control w-75" %>
      </div>
      <div class="col-4 form-inline">
        <%= f.text_field :first_name_kana, class: "form-control w-75" %>
      </div>
    </div>
    
    <div class="my-4 mx-2 form-group row d-flex small justify-content-start">
      <%= f.label :postal_code, "郵便番号", class: "col-3 col-form-label" %>
      <div class="col-9">
        <%= f.text_field :postal_code, class: "form-control w-75" %>
      </div>
    </div>
    
    <div class="my-4 mx-2 form-group row d-flex small justify-content-start">
      <%= f.label :address, "住所", class: "col-3 col-form-label" %>
      <div class="col-9">
        <%= f.text_field :address, class: "form-control w-75" %>
      </div>
    </div>
    
    <div class="my-4 mx-2 form-group row d-flex small justify-content-start">
      <%= f.label :telephone_number, "電話番号", class: "col-3 col-form-label" %>
      <div class="col-9">
        <%= f.text_field :telephone_number, class: "form-control w-75" %>
      </div>
    </div>
    <div class="my-4 mx-2 form-group row d-flex small justify-content-start">
      <%= f.label :email, "メールアドレス", class: "col-3 col-form-label" %>
      <div class="col-9">
      <%= f.text_field :email, class: "form-control w-75" %>
      </div>
    </div>
    <div class="my-4 mx-2 form-group row d-flex small justify-content-start mb-5 pb-5">
      <%= f.submit "編集内容を保存", class: "btn btn-success d-block col-4 col-md-2 mr-5" %>
      <%= link_to("退会する",customer_confirm_path, class: "btn btn-danger col-4 col-md-2") %>
    </div>
  <% end %>
      
</div>

app/views/customers/show.html.erb
<div class="container px-2">
  
  <div class=" my-4 mx-2 row d-flex justify-content-start">
    <h2>マイページ</h2>
  </div>
  <div class=" my-4 mx-2 row d-flex justify-content-start">
      <span class="font-weight-bold col-3">登録情報</span>
      <%= link_to("編集する", customer_edit_path, class: "btn btn-success col-2") %>
  </div>
  <div class=" my-4 mx-2 row d-flex justify-content-start">
    <table class="table table-bordered w-75">
        <tr>
          <th class="table-secondary w-25">氏名</th>
          <td><%= @customer.last_name + @customer.first_name %></td>
        </tr>
        <tr>
          <th class="table-secondary w-25">カナ</th>
          <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th class="table-secondary w-25">郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th class="table-secondary w-25">住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th class="table-secondary w-25">電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th class="table-secondary w-25">メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
    </table>
  </div>
  
  <div class=" my-4 mx-2 row d-flex justify-content-start">
    <span class="col-3 font-weight-bold">配送先</span>
    <%= link_to("一覧を見る",addresses_path, class: "btn btn-primary col-2") %>
  </div>
  <div class=" my-4 mx-2 row d-flex justify-content-start mb-5 pb-5">
    <span class="font-weight-bold col-3">注文履歴</span>
    <%= link_to("一覧を見る",orders_path, class: "btn btn-primary col-2") %>
  </div>
  
</div>