config/routes.rb
Rails.application.routes.draw do
  
  root :to => "homes#top"
  get "about", to: "homes#about", as: "about"
  resources :items, only: [:index,:show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  
  # cart_items routes
  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete "cart_items", to: "cart_items#destroy_all", as: "destroy_all_cart_items"
  

  # orders routes
  resources :orders, only: [:new, :create, :index, :show] do 
    collection do
      get :confirm
      get :complete
    end
  end
  
  # customers routes
  get "customers/mypage", to: "customers#show", as: "customer_mypage"
  get "customers/confirm", to: "customers#confirm", as: "customer_confirm"
  get "customers/edit", to: "customers#edit", as: "customer_edit"
  patch "customers", to: "customers#update", as: "customer_update"
  
  
  
  namespace :admin do
    root :to => "homes#top"
    resources :genres, only: [:index,:create,:edit,:update]
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end
  
  
  devise_for :customers, controllers: {
    sessions:        'customers/sessions',
    passwords:       'customers/passwords',
    registrations:   'customers/registrations',
  }
  
  devise_for :admins, path: "admin",controllers: {
    sessions:        'admins/sessions',
    passwords:       'admins/passwords',
    registrations:   'admins/registrations',
  }
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  # validates_presence_of :image
  
  has_many :cart_items, dependent: :destroy
  has_one :order_item,  dependent: :destroy
  
  belongs_to :genre
  
  
  validates :genre_id       , presence: true
  validates :name           , presence: true
  validates :image          , presence: true
  validates :introduction   , presence: true
  validates :price          , presence: true , numericality: {only_integer: true, greater_than: 0}
  validates :is_active                       , inclusion: [true,false]
  
  def taxed_price
    return (price * 1.1).to_i
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def index
    @items = Item.page(params[:page])
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "New Item was successfully registerd!"
      redirect_to(admin_item_path(@item.id))
    else
      err_msg = "error! Failed to register item\n"
      @item.errors.full_messages.each do |msg|
        err_msg += msg + "\n"
      end
      flash[:alert] = err_msg
      render(:new)
    end
      
      
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def show
    @item  = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "Item was successfully updated"
      redirect_to(admin_item_path(@item.id))
    else
      err_msg = "error! Failed to update data\n"
      @item.errors.full_messages.each do |msg|
        err_msg += msg + "\n"
      end
      flash[:alert] = err_msg
      render :edit
    end
  end
  
  private
  def item_params
    params.require(:item).permit(:genre_id,:name,:image,:introduction,:price,:is_active)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  skip_before_action :authenticate_customer!
  
  def index
    @genres = Genre.all
    
    if params[:genre_id]
      @count = Item.where(genre_id: params[:genre_id]).count
      @items = Item.where(genre_id: params[:genre_id]).page(params[:page]).per(8)
      @title = Genre.find(params[:genre_id]).name
      
    elsif params[:searchword]
      @count = Item.where("name LIKE ?", "%#{params[:searchword]}%").count
      @items = Item.where("name LIKE ?", "%#{params[:searchword]}%").page(params[:page]).per(8)
      @title = "\"" + params[:searchword] + "\" での検索結果"
      
    else
      @count = Item.count
      @items = Item.page(params[:page]).per(8)
      @title = "商品"
      
    end
  end
  
  def show
    @item = Item.find(params[:id])
    @genres = Genre.all
    @cart_item = CartItem.new()
  end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<%= render(partial: "/layouts/genrebar-horizon", locals: {genres: @genres}) %>
<div class="container px-2 vh-100">
  
  <div class=" my-4 mx-2 row d-flex justify-content-start">
    <%= render(partial: "/layouts/genrebar", locals: {genres: @genres}) %>
    <div class="col-12 col-md-9 mx-auto">
        <h2>
          <%= @title %>一覧<span class="small">(全<%= @count %>件)</span>
        </h2>
        
        <div class="row my-5 h-50">
          <% @items.each do |item| %>
            <div class="col-3 my-4">
              <%= link_to(item_path(item.id))  do %>
                <%= attachment_image_tag(item, :image, fallback: "no_image.jpg", size: "150x150") %>
              <% end %><br>
              <%= item.name %><br>
              ￥<%= delimitate(item.taxed_price) %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-12 col-md-9">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<%= render(partial: "/layouts/genrebar-horizon", locals: {genres: @genres}) %>
<div class="container px-2 vh-100">
  
  <div class=" my-4 mx-2 row d-flex justify-content-start">
    <%= render(partial: "/layouts/genrebar", locals: {genres: @genres}) %>
    <div class="col-md-5 col-12 d-flex justify-content-center">
      <%= attachment_image_tag(@item, :image, fallback: "no_image.jpg", size: "250x250") %>
    </div>
    <div class="col-md-5 col-12 d-flex flex-column">
      <h3>
        <%= @item.name %>
      </h3>
      <p>
        <%= @item.introduction %>
      </p>
      <p>
        <span class="font-weight-bold">￥<%= delimitate(@item.taxed_price) %>円</span>(税込)
      </p>
      <% if customer_signed_in? %>
        <%= form_with(model: @cart_item, url: cart_items_path,local: true, class: "form-group") do |f| %>
          <%= f.hidden_field :customer_id, value: current_customer.id %>
          <%= f.hidden_field :item_id, value: @item.id %>
          <%= f.select :amount, *[1..9], {prompt: "個数選択"}, {class: "form-control-sm w-50 d-inline-block mb-4"} %>
          <%= f.submit "カートに入れる", class: "btn btn-success d-inline-block" %>
        <% end %>
      <% end %>
      </div>
  </div>

</div>