config/routes.rb
Rails.application.routes.draw do
  
  root :to => "homes#top"
  get "about", to: "homes#about", as: "about"
  resources :items, only: [:index,:show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  
  # cart_items routes
  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete "cart_items", to: "cart_items#destroy_all", as: "destroy_all_cart_items"
  

  # orders routes
  resources :orders, only: [:new, :create, :index, :show] do 
    collection do
      get :confirm
      get :complete
    end
  end
  
  # customers routes
  get "customers/mypage", to: "customers#show", as: "customer_mypage"
  get "customers/confirm", to: "customers#confirm", as: "customer_confirm"
  get "customers/edit", to: "customers#edit", as: "customer_edit"
  patch "customers", to: "customers#update", as: "customer_update"
  
  
  
  namespace :admin do
    root :to => "homes#top"
    resources :genres, only: [:index,:create,:edit,:update]
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end
  
  
  devise_for :customers, controllers: {
    sessions:        'customers/sessions',
    passwords:       'customers/passwords',
    registrations:   'customers/registrations',
  }
  
  devise_for :admins, path: "admin",controllers: {
    sessions:        'admins/sessions',
    passwords:       'admins/passwords',
    registrations:   'admins/registrations',
  }
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_err-msg.html.erb
 <div class="container-fluid">
      <div class="row">
        <div class="col">
          <% flash.each do |type, msg| %>
            <% if type == "notice" %>
              <div class="alert alert-success">
            <% elsif type == "alert" %>
              <div class="alert alert-danger">
            <% end %>
                <%= h(msg).gsub(/\n/,"<br>").html_safe %>
              </div>
          <% end %>
        </div>
      </div>
  </div>

app/views/layouts/_genrebar-horizon.html.erb
<!--md以下用　horizontal-->

<div class="accordion d-md-none" id="accordion-4">
  <div class="card bg-light">
    <div class="card-header" id="header-4a">
      <button class="btn btn-link text-success font-weight-bold" type="button"
          data-toggle="collapse" data-target="#card-4a"
          aria-expanded="true" aria-controls="card-4a">
        ジャンル検索
      </button>
    </div>
    <div id="card-4a" class="collapse"
        aria-labelledby="header-4a" data-parent="#accordion-4">
        <% genres.each do |genre| %>
          <div class="card-body">
            <%= link_to(genre.name, items_path(genre_id: genre.id), class: "text-success") %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/_genrebar.html.erb
<!-- md以上用 vertical-->

<div class="list-group col-2 d-md-block d-none small">

  <li class="list-group-item list-group-item-success">ジャンル検索</li>
  <% genres.each do |genre| %>
    <li class="list-group-item">
      <%= link_to(genre.name, items_path(genre_id: genre.id), class: "text-success") %>
    </li>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md bg-info navbar-dark">
        <a class="navbar-brand" href="/">Nagano Cake</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler1" aria-controls="navbarToggler1">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-md-end" id="navbarToggler1">
          <ul class="navbar-nav flex-md-column ">
            <div class="d-flex flex-column flex-md-row">
              <li class="nav-item mr-4 my-2">
                <% if admin_signed_in? %>
                  <%= link_to("商品一覧",admin_items_path,class: "text-white") %>
                <% elsif customer_signed_in? %>
                  <%= link_to("マイページ", customer_mypage_path, class: "text-white") %>
                <% else %>
                  <%= link_to("About",about_path, class: "text-white") %>
                <% end %>
              </li>
              <li class="nav-item mr-4 my-2">
                <% if admin_signed_in? %>
                  <%= link_to("会員一覧",admin_customers_path,class: "text-white") %>
                <% else %>
                  <%= link_to("商品一覧", items_path, class: "text-white") %>
                <% end %>
              </li>
              <li class="nav-item mr-4 my-2">
                <% if admin_signed_in? %>
                  <%= link_to("注文履歴一覧", admin_root_path, class: "text-white") %>
                <% elsif customer_signed_in? %>
                  <%= link_to("カート", cart_items_path, class: "text-white") %>
                <% else %>
                  <%= link_to("新規登録", new_customer_registration_path, class: "text-white") %>
                <% end %>
              </li>
              <li class="nav-item mr-4 my-2">
                <% if admin_signed_in? %>
                  <%= link_to("ジャンル一覧", admin_genres_path, class: "text-white") %>
                <% elsif customer_signed_in? %>
                  <%= link_to("ログアウト", destroy_customer_session_path, method: :delete, class: "text-white") %>
                <% else %>
                  <%= link_to("ログイン", new_customer_session_path, class: "text-white") %>
                <% end %>
              </li>
              <% if admin_signed_in? %>
                <li class="nav-item mr-4 my-2">
                  <%= link_to("ログアウト", destroy_admin_session_path, method: :delete,class: "text-white") %>                
                </li>
              <% end %>
            </div>
            
            <div>
              <li class="nav-item mr-4 my-2">
                <%= form_with(url: items_path, method: "get",\
                              class: "input-group", local: true) do |f| %>
                  <%= f.text_field(:searchword, {placeholder: "Seach", class: "form-control"}) %>
                    <span class="input-group-btn">
                      <button type="submit" class="bg-white btn">
                          <i class="fa fa-search" aria-hidden="true"></i>
                      </button>
                    </span>
                <% end %>
              </li>
            </div>
            
          </ul>
        </div>
      </nav>
    
    </header>
    
    <main>
      <%= render(partial: "/layouts/err-msg") %>
      <%= yield %>
    </main>
    
    <footer class="my-4">
    </footer>
    
  </body>
</html>